version: "3.9"
services:
  
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      - .env
    volumes: 
      - /23_paskal_mysql:/var/lib/mysql
    container_name: paskal-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "9001:80"
    environment:
      - .env
    volumes:
      - /sessionss
    container_name: paskal-phpmyadmin-app
  express:
    depends_on: 
      - mysql
    build: .
    networks:
      - backend
    environment:
      - .env
    volumes:
      - ./express-files:/app/public/images
    ports:
      - "9000:9000"
    container_name: paskal-express-app
networks:
  backend: